


services:

  app:
    build: .
    container_name: image-server-2
    restart: unless-stopped
    volumes:
      - images:/app/images
      - logs:/app/logs
    expose:
      - "8000"

    environment:
      PYTHONUNBUFFERED: 1

  nginx:
    image: nginx:1.27-alpine
    container_name: image-server-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/images:ro
    ports: 
      - "8080:80"
      - "80:80"
    restart: unless-stopped    



volumes:
  images:
  logs: